# -*- coding: utf-8 -*-
"""Nhận diện chữ cái bằng ký hiệu tay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug9dv4-KiFWGOwUZB3Pec2n1Ab04vYzW
"""

from google.colab import drive
drive.mount('/content/drive')

#Giải nén dataset trong Colab
import zipfile
import os
zip_path = '/content/drive/MyDrive/datasets/archive.zip'
extract_path = '/content/archive'
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Giải nén xong!")

# Cài thư viện cần thiết
!pip install tensorflow matplotlib scikit-learn

"""**Load & Chuẩn bị dữ liệu**"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Đường dẫn folder train/test
train_dir = '/content/archive/asl_alphabet_train/asl_alphabet_train'
test_dir = '/content/archive/asl_alphabet_test/asl_alphabet_test'

# Chuẩn bị generator
datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_data = datagen.flow_from_directory(
    train_dir,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical',
    subset='training'
)

val_data = datagen.flow_from_directory(
    train_dir,
    target_size=(64, 64),
    batch_size=32,
    class_mode='categorical',
    subset='validation'
)

"""**Xây dựng CNN Model**"""

from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(64,64,3)),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),

    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(train_data.num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

"""**Train model**"""

history = model.fit(
    train_data,
    epochs=10,
    validation_data=val_data
)

"""**Lưu model về Google Drive**"""

model.save('/content/drive/MyDrive/asl_cnn_model.h5')
print("Model đã lưu vào Google Drive!")

"""**Test model với ảnh**"""

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = '/content/archive/asl_alphabet_test/asl_alphabet_test/E_test.jpg'  # đổi thành ảnh test
img = image.load_img(img_path, target_size=(64,64))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0) / 255.0

pred = model.predict(x)
class_index = np.argmax(pred)
class_labels = list(train_data.class_indices.keys())

print("Dự đoán:", class_labels[class_index])